### ISSUE TITLE
gitflow for Examples?

### ISSUE THREAD

**Issue by bpalmintier** [GMLC-TDC/HELICS-Examples#2]
Should we migrate HELICS-Examples to use a gitflow or gitflow-like structure/workflow? Notably switching to have a develop branch from which we occassionally pull ready to share versions to masters, and a more strict habit of using new branches and pull requests.

Similarly I'd propose adopting some form of semantic versioning, but perhaps where the first and second numbers match those from HELICS-src, but the third number is kept separate to mange internal updates for examples.

Thoughts?

**Comment by phlptp** [comment]
I think this is a good idea once this repo is operational with CI integration complete.  It might be a good idea to start that alignment once we get to the 2.0 release and have the examples aligned with that release.    I am not sure it makes sense to do it with the 1.X release as I think we will be trying to migrate away from that as quickly as possible once fully operational.

**Comment by afisher1** [comment]
I think this is a good idea as well.

**Comment by phlptp** [comment]
I think this issue will be closed when we tag a 2.3 release for the examples, then we will pretty much be on track for making the repo match up with the main HELICS repo and using gitflow.

**Comment by phlptp** [comment]
2.3 tagged
