### ISSUE TITLE
v3 API for sending messages to/from endpoints

### ISSUE THREAD

**Issue by allisonmcampbell** [GMLC-TDC/HELICS-Examples#37]
The current working Python API in the v3 alpha 2 release for sending messages is:

```
h.helicsEndpointSendBytesTo(endpoint: HelicsEndpoint, destination: str, data: bytes)
```

If the endpoint has a default destination, this looks like:

```
h.helicsEndpointSendBytesTo(endpoint: HelicsEndpoint, "", str(message).encode())
```

```
$ helics_app --version
3.0.0-alpha.2-helics3-gd501f17 (2020-11-10)
```

Once the v3 release is complete, we should review the APIs to confirm/update for consistency.

Should we be using `h.helicsEndpointSendBytes' ? 

Or this ?

```
h.helicsEndpointSendBytesTo(endpoint: HelicsEndpoint, str(message).encode(), "")
```

**Comment by trevorhardy** [comment]
The [fundamental endpoint example](https://github.com/GMLC-TDC/HELICS-Examples/tree/main/user_guide_examples/fundamental/fundamental_message_comm/endpoints) uses the following and is working in v3.1:

```
h.helicsEndpointSendBytesTo(endpoint, str(message), "")
```
