### ISSUE TITLE
Convert fundamental final example to Pythonic API implementation?

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS-Examples#55]
I don't know where the fundamental final example fits into the flow of the examples but given that it is largely a repeat of the fundamental integration example, it seems like a good candidate for conversion to the Pythonic API. Let me know if you think this is a good idea.

**Comment by trevorhardy** [comment]
Fundamental final example removed.

**Comment by nightlark** [comment]
The user guide still has a handful of references to the fundamental_final example:

```
user-guide/examples/fundamental_examples/fundamental_examples_index.md:12:    fundamental_final
user-guide/examples/Examples.md:9:    fundamental_final
user-guide/fundamental_topics/interface_configuration.md:111:The following example of a federate interface configuration with the PyHELICS API comes from the [Fundamental Final Example](../examples/fundamental_examples/fundamental_final.md). This co-simulation has exactly the same interface configuration as the Combination Federation above. The only difference is that the federate interfaces are configured with the PyHELICS API.
```

**Comment by trevorhardy** [comment]
Addressed in [PR 2225](https://github.com/GMLC-TDC/HELICS/pull/2225) in the main HELICS repo.
