### ISSUE TITLE
Advanced Orchestration example references files that don't exist in the same folder

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS-Examples#58]
There is no folder for the advanced orchestration example that contains `Battery.py`, `Charger.py`, and `make_samples.py` -- based on the code in https://github.com/GMLC-TDC/HELICS-Examples/blob/main/user_guide_examples/advanced/advanced_orchestration/simple/ev_uq_example.yaml#L15 which expects all 3 of these files to be in the same folder (`$(SPECROOT)`). My best guess is that line 15 should read `$(SPECROOT)/simple/make_samples_merlin.py`.

**Comment by trevorhardy** [comment]
@allisonmcampbell, can you get this sorted out today (Monday, 29th)? We're trying to get a v3.1 release out and would like to have all our ducks in a row.

**Comment by allisonmcampbell** [comment]
yes, seeing this now. I'll report back when it's done.

**Comment by allisonmcampbell** [comment]
Yes, @nightlark , your proposed solution makes sense:

 line 15 should read

```
 $(SPECROOT)/simple/make_samples_merlin.py
```

**Comment by trevorhardy** [comment]
@allisonmcampbell, is this resolved?
