### ISSUE TITLE
Create example in MATLAB

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS-Examples#64]
Using the MATLAB language, create an example

**Comment by trevorhardy** [comment]
Waiting on completion of the MATLAB language support: https://github.com/GMLC-TDC/HELICS/issues/1516

**Comment by trevorhardy** [comment]
MATLAB example should be a conversion of the advanced default example

**Comment by trevorhardy** [comment]
@eranschweitzer, was this on your radar? I see I assigned it to you but can't remember if we discussed it recently.

**Comment by eranschweitzer** [comment]
@trevorhardy, yes it was. You can see that my pull request #73 is linked here on the right 😉
