### ISSUE TITLE
Change "Federate Integration via HELICS APIs" Code To Be Modification Of "Base Example Co-Simulation"

### ISSUE THREAD

**Issue by awkbr549** [GMLC-TDC/HELICS-Examples#95]
## Summary
Replace the `fundamental_integration` example, which currently is a modification of the complex example `fundamental_message_comm/filter_native`, with a modification of the simpler example `fundamental_default`.

## Details
As I was going through the documentation, the increase in complexity (with respect to the code) going from the "Base Example Co-Simulation" to the "Federate Integration via HELICS APIs" was quite a jump. Upon continuing into the "Federate Message + Communication Configuration: Combination Federation with Native HELICS Filters" example, I realized there may be have been an oversight with respect to the construction of the "Federate Integration via HELICS APIs" example.

The fundamental example "Federate Integration via HELICS APIs" found in the documentation at [https://docs.helics.org/en/latest/user-guide/examples/fundamental_examples/fundamental_fedintegration.html](https://docs.helics.org/en/latest/user-guide/examples/fundamental_examples/fundamental_fedintegration.html) describes the example "Base Example Co-Simulation" with the simple modification of using the HELICS Python API within the code instead of using an external configuration file.

However, the code found in the repository at [https://github.com/GMLC-TDC/HELICS-Examples/tree/main/user_guide_examples/fundamental/fundamental_integration](https://github.com/GMLC-TDC/HELICS-Examples/tree/main/user_guide_examples/fundamental/fundamental_integration) is a modification of the more complex example "Federate Message + Communication Configuration: Combination Federation with Native HELICS Filters" found in the documentation at [https://docs.helics.org/en/latest/user-guide/examples/fundamental_examples/fundamental_native_filter.html](https://docs.helics.org/en/latest/user-guide/examples/fundamental_examples/fundamental_native_filter.html).

Additionally, the image found in the "Federate Integration via HELICS APIs" shows a version of the `fundamental_integration` directory in a past state, seemingly some time before commit 6b02754.

**Comment by trevorhardy** [comment]
Rather than changing the example, I've changed the flow of the examples to address endpoints first and then go on to API-based configuration. This way the API-based configuration covers more of the HELICS components and is thus a more comprehensive reference.
